# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/jesus/OneDrive/Masaüstü/PyQt5/PROJELER/DERS PRO/Kütüphane_tabWigdet/tab_wigdet.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2861, 1060)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/bookshelf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("#verticalLayout_4{\n"
"    \n"
"    background-color: rgb(255, 170, 127);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(70, 50))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        self.groupBox = QtWidgets.QGroupBox(self.tab_home)
        self.groupBox.setGeometry(QtCore.QRect(0, -10, 2211, 981))
        self.groupBox.setMaximumSize(QtCore.QSize(2999, 20090))
        self.groupBox.setStyleSheet("#groupBox{\n"
"    \n"
"        \n"
"    border-image: url(:/icons/singin_borded_imge.jpg);\n"
"    \n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pbt_giris = QtWidgets.QPushButton(self.groupBox)
        self.pbt_giris.setGeometry(QtCore.QRect(260, 200, 311, 111))
        self.pbt_giris.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons_action/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbt_giris.setIcon(icon1)
        self.pbt_giris.setObjectName("pbt_giris")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 571, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lne_giris = QtWidgets.QLineEdit(self.splitter)
        self.lne_giris.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lne_giris.setObjectName("lne_giris")
        self.verticalLayout_3.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.lne_parola = QtWidgets.QLineEdit(self.splitter_2)
        self.lne_parola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lne_parola.setObjectName("lne_parola")
        self.verticalLayout_3.addWidget(self.splitter_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_home, icon2, "")
        self.tab_Kitaplar = QtWidgets.QWidget()
        self.tab_Kitaplar.setObjectName("tab_Kitaplar")
        self.label_3 = QtWidgets.QLabel(self.tab_Kitaplar)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setObjectName("label_3")
        self.tablw_Kitap_listesi = QtWidgets.QTableWidget(self.tab_Kitaplar)
        self.tablw_Kitap_listesi.setEnabled(True)
        self.tablw_Kitap_listesi.setGeometry(QtCore.QRect(0, 50, 1481, 961))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tablw_Kitap_listesi.setFont(font)
        self.tablw_Kitap_listesi.setFrameShape(QtWidgets.QFrame.Panel)
        self.tablw_Kitap_listesi.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tablw_Kitap_listesi.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tablw_Kitap_listesi.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablw_Kitap_listesi.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablw_Kitap_listesi.setDragEnabled(False)
        self.tablw_Kitap_listesi.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tablw_Kitap_listesi.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablw_Kitap_listesi.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablw_Kitap_listesi.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tablw_Kitap_listesi.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tablw_Kitap_listesi.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tablw_Kitap_listesi.setShowGrid(True)
        self.tablw_Kitap_listesi.setGridStyle(QtCore.Qt.SolidLine)
        self.tablw_Kitap_listesi.setCornerButtonEnabled(True)
        self.tablw_Kitap_listesi.setRowCount(9999)
        self.tablw_Kitap_listesi.setColumnCount(6)
        self.tablw_Kitap_listesi.setObjectName("tablw_Kitap_listesi")
        self.tablw_Kitap_listesi.horizontalHeader().setCascadingSectionResizes(False)
        self.tablw_Kitap_listesi.horizontalHeader().setDefaultSectionSize(240)
        self.tablw_Kitap_listesi.verticalHeader().setDefaultSectionSize(55)
        self.frame_2 = QtWidgets.QFrame(self.tab_Kitaplar)
        self.frame_2.setGeometry(QtCore.QRect(1490, 50, 391, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(112, 0, 56);\n"
"    \n"
"    \n"
"    \n"
"}")
        self.frame_2.setObjectName("frame_2")
        self.pbt_kitap_ara = QtWidgets.QPushButton(self.frame_2)
        self.pbt_kitap_ara.setEnabled(True)
        self.pbt_kitap_ara.setGeometry(QtCore.QRect(90, 160, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_kitap_ara.setFont(font)
        self.pbt_kitap_ara.setStyleSheet("color: rgb(255, 170, 0);\n"
"background-color: rgb(39, 118, 118);\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbt_kitap_ara.setIcon(icon3)
        self.pbt_kitap_ara.setIconSize(QtCore.QSize(24, 24))
        self.pbt_kitap_ara.setObjectName("pbt_kitap_ara")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 31, 381, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.splitter_3.setFont(font)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setObjectName("label_4")
        self.lne_kitap = QtWidgets.QLineEdit(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lne_kitap.setFont(font)
        self.lne_kitap.setStyleSheet("\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.lne_kitap.setObjectName("lne_kitap")
        self.verticalLayout.addWidget(self.splitter_3)
        self.splitter_4 = QtWidgets.QSplitter(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.splitter_4.setFont(font)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_5 = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setObjectName("label_5")
        self.lne_yazar_ = QtWidgets.QLineEdit(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lne_yazar_.setFont(font)
        self.lne_yazar_.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lne_yazar_.setObjectName("lne_yazar_")
        self.verticalLayout.addWidget(self.splitter_4)
        self.pbt_listele = QtWidgets.QPushButton(self.frame_2)
        self.pbt_listele.setGeometry(QtCore.QRect(120, 290, 171, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbt_listele.setFont(font)
        self.pbt_listele.setStyleSheet("color: rgb(255, 170, 0);\n"
"background-color: rgb(39, 118, 118);\n"
"\n"
"\n"
"")
        self.pbt_listele.setObjectName("pbt_listele")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_Kitaplar, icon4, "")
        self.tab_kullanici_ekle = QtWidgets.QWidget()
        self.tab_kullanici_ekle.setObjectName("tab_kullanici_ekle")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_kullanici_ekle)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 40, 351, 211))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_5 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_6 = QtWidgets.QLabel(self.splitter_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);\n"
"")
        self.label_6.setObjectName("label_6")
        self.lne_ad = QtWidgets.QLineEdit(self.splitter_5)
        self.lne_ad.setText("")
        self.lne_ad.setObjectName("lne_ad")
        self.verticalLayout_4.addWidget(self.splitter_5)
        self.splitter_6 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.lne_soyad = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lne_soyad.setFont(font)
        self.lne_soyad.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);")
        self.lne_soyad.setObjectName("lne_soyad")
        self.lnek_soyad = QtWidgets.QLineEdit(self.splitter_6)
        self.lnek_soyad.setText("")
        self.lnek_soyad.setObjectName("lnek_soyad")
        self.verticalLayout_4.addWidget(self.splitter_6)
        self.splitter_13 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.lne_sinif = QtWidgets.QLabel(self.splitter_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lne_sinif.setFont(font)
        self.lne_sinif.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);\n"
"")
        self.lne_sinif.setObjectName("lne_sinif")
        self.lnek_sinif = QtWidgets.QLineEdit(self.splitter_13)
        self.lnek_sinif.setText("")
        self.lnek_sinif.setObjectName("lnek_sinif")
        self.verticalLayout_4.addWidget(self.splitter_13)
        self.splitter_14 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.lne_gsm_no = QtWidgets.QLabel(self.splitter_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lne_gsm_no.setFont(font)
        self.lne_gsm_no.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);")
        self.lne_gsm_no.setObjectName("lne_gsm_no")
        self.lnek_gsm_no = QtWidgets.QLineEdit(self.splitter_14)
        self.lnek_gsm_no.setText("")
        self.lnek_gsm_no.setObjectName("lnek_gsm_no")
        self.verticalLayout_4.addWidget(self.splitter_14)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_kullanici_ekle)
        self.layoutWidget3.setGeometry(QtCore.QRect(1210, 10, 471, 321))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.layoutWidget3)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_5.addWidget(self.calendarWidget)
        self.splitter_15 = QtWidgets.QSplitter(self.tab_kullanici_ekle)
        self.splitter_15.setGeometry(QtCore.QRect(380, 110, 161, 19))
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.tablw_Kitap_listesi_2 = QtWidgets.QTableWidget(self.tab_kullanici_ekle)
        self.tablw_Kitap_listesi_2.setEnabled(True)
        self.tablw_Kitap_listesi_2.setGeometry(QtCore.QRect(670, 40, 491, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tablw_Kitap_listesi_2.setFont(font)
        self.tablw_Kitap_listesi_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.tablw_Kitap_listesi_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tablw_Kitap_listesi_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tablw_Kitap_listesi_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablw_Kitap_listesi_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablw_Kitap_listesi_2.setDragEnabled(False)
        self.tablw_Kitap_listesi_2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tablw_Kitap_listesi_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablw_Kitap_listesi_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablw_Kitap_listesi_2.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tablw_Kitap_listesi_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tablw_Kitap_listesi_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tablw_Kitap_listesi_2.setShowGrid(True)
        self.tablw_Kitap_listesi_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tablw_Kitap_listesi_2.setCornerButtonEnabled(True)
        self.tablw_Kitap_listesi_2.setRowCount(12)
        self.tablw_Kitap_listesi_2.setColumnCount(2)
        self.tablw_Kitap_listesi_2.setObjectName("tablw_Kitap_listesi_2")
        self.tablw_Kitap_listesi_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tablw_Kitap_listesi_2.horizontalHeader().setDefaultSectionSize(225)
        self.tablw_Kitap_listesi_2.verticalHeader().setDefaultSectionSize(43)
        self.pbt_kul_kaydet = QtWidgets.QPushButton(self.tab_kullanici_ekle)
        self.pbt_kul_kaydet.setGeometry(QtCore.QRect(1700, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_kul_kaydet.setFont(font)
        self.pbt_kul_kaydet.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"\n"
"color: rgb(0, 0, 0);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbt_kul_kaydet.setIcon(icon5)
        self.pbt_kul_kaydet.setIconSize(QtCore.QSize(35, 35))
        self.pbt_kul_kaydet.setCheckable(False)
        self.pbt_kul_kaydet.setChecked(False)
        self.pbt_kul_kaydet.setAutoRepeat(False)
        self.pbt_kul_kaydet.setAutoExclusive(False)
        self.pbt_kul_kaydet.setAutoDefault(False)
        self.pbt_kul_kaydet.setDefault(True)
        self.pbt_kul_kaydet.setFlat(False)
        self.pbt_kul_kaydet.setObjectName("pbt_kul_kaydet")
        self.label_14 = QtWidgets.QLabel(self.tab_kullanici_ekle)
        self.label_14.setGeometry(QtCore.QRect(670, 0, 249, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.tablw_kullanicilar = QtWidgets.QTableWidget(self.tab_kullanici_ekle)
        self.tablw_kullanicilar.setEnabled(True)
        self.tablw_kullanicilar.setGeometry(QtCore.QRect(0, 350, 1851, 561))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tablw_kullanicilar.setFont(font)
        self.tablw_kullanicilar.setFrameShape(QtWidgets.QFrame.Panel)
        self.tablw_kullanicilar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tablw_kullanicilar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tablw_kullanicilar.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tablw_kullanicilar.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablw_kullanicilar.setDragEnabled(False)
        self.tablw_kullanicilar.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tablw_kullanicilar.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablw_kullanicilar.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablw_kullanicilar.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tablw_kullanicilar.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tablw_kullanicilar.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tablw_kullanicilar.setShowGrid(True)
        self.tablw_kullanicilar.setGridStyle(QtCore.Qt.SolidLine)
        self.tablw_kullanicilar.setCornerButtonEnabled(True)
        self.tablw_kullanicilar.setRowCount(9999)
        self.tablw_kullanicilar.setColumnCount(9)
        self.tablw_kullanicilar.setObjectName("tablw_kullanicilar")
        self.tablw_kullanicilar.horizontalHeader().setCascadingSectionResizes(False)
        self.tablw_kullanicilar.horizontalHeader().setDefaultSectionSize(200)
        self.tablw_kullanicilar.verticalHeader().setVisible(False)
        self.tablw_kullanicilar.verticalHeader().setDefaultSectionSize(55)
        self.tablw_kullanicilar.verticalHeader().setHighlightSections(True)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_kullanici_ekle)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 30, 241, 121))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 20, 231, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_11 = QtWidgets.QSplitter(self.layoutWidget_2)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.label_7 = QtWidgets.QLabel(self.splitter_11)
        self.label_7.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);")
        self.label_7.setObjectName("label_7")
        self.lnek_kitap_ad = QtWidgets.QLineEdit(self.splitter_11)
        self.lnek_kitap_ad.setReadOnly(True)
        self.lnek_kitap_ad.setObjectName("lnek_kitap_ad")
        self.verticalLayout_6.addWidget(self.splitter_11)
        self.splitter_12 = QtWidgets.QSplitter(self.layoutWidget_2)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.label_13 = QtWidgets.QLabel(self.splitter_12)
        self.label_13.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);")
        self.label_13.setObjectName("label_13")
        self.lne_kullanci_yazar = QtWidgets.QLineEdit(self.splitter_12)
        self.lne_kullanci_yazar.setReadOnly(True)
        self.lne_kullanci_yazar.setObjectName("lne_kullanci_yazar")
        self.verticalLayout_6.addWidget(self.splitter_12)
        self.splitter_16 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_16.setGeometry(QtCore.QRect(0, 120, 249, 42))
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.cmb_teslim = QtWidgets.QComboBox(self.tab_kullanici_ekle)
        self.cmb_teslim.setGeometry(QtCore.QRect(1720, 30, 161, 31))
        self.cmb_teslim.setObjectName("cmb_teslim")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmb_teslim.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmb_teslim.addItem(icon7, "")
        self.pbt_guncele = QtWidgets.QPushButton(self.tab_kullanici_ekle)
        self.pbt_guncele.setGeometry(QtCore.QRect(1700, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_guncele.setFont(font)
        self.pbt_guncele.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"\n"
"color: rgb(0, 0, 0);")
        self.pbt_guncele.setIcon(icon5)
        self.pbt_guncele.setIconSize(QtCore.QSize(35, 35))
        self.pbt_guncele.setCheckable(False)
        self.pbt_guncele.setChecked(False)
        self.pbt_guncele.setAutoRepeat(False)
        self.pbt_guncele.setAutoExclusive(False)
        self.pbt_guncele.setAutoDefault(False)
        self.pbt_guncele.setDefault(True)
        self.pbt_guncele.setFlat(False)
        self.pbt_guncele.setObjectName("pbt_guncele")
        self.pbt_ara = QtWidgets.QPushButton(self.tab_kullanici_ekle)
        self.pbt_ara.setGeometry(QtCore.QRect(1700, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbt_ara.setFont(font)
        self.pbt_ara.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"\n"
"color: rgb(0, 0, 0);")
        self.pbt_ara.setIcon(icon5)
        self.pbt_ara.setIconSize(QtCore.QSize(35, 35))
        self.pbt_ara.setCheckable(False)
        self.pbt_ara.setChecked(False)
        self.pbt_ara.setAutoRepeat(False)
        self.pbt_ara.setAutoExclusive(False)
        self.pbt_ara.setAutoDefault(False)
        self.pbt_ara.setDefault(True)
        self.pbt_ara.setFlat(False)
        self.pbt_ara.setObjectName("pbt_ara")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/add-friend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_kullanici_ekle, icon8, "")
        self.tab_Kitap_ekle = QtWidgets.QWidget()
        self.tab_Kitap_ekle.setObjectName("tab_Kitap_ekle")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_Kitap_ekle)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 20, 1141, 351))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_7 = QtWidgets.QSplitter(self.layoutWidget4)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.label_8 = QtWidgets.QLabel(self.splitter_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);\n"
"")
        self.label_8.setObjectName("label_8")
        self.lne_kitap_adi = QtWidgets.QLineEdit(self.splitter_7)
        self.lne_kitap_adi.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lne_kitap_adi.setObjectName("lne_kitap_adi")
        self.verticalLayout_2.addWidget(self.splitter_7)
        self.splitter_8 = QtWidgets.QSplitter(self.layoutWidget4)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_9 = QtWidgets.QLabel(self.splitter_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);\n"
"")
        self.label_9.setObjectName("label_9")
        self.lne_yazar = QtWidgets.QLineEdit(self.splitter_8)
        self.lne_yazar.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lne_yazar.setObjectName("lne_yazar")
        self.verticalLayout_2.addWidget(self.splitter_8)
        self.splitter_9 = QtWidgets.QSplitter(self.layoutWidget4)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label_10 = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);\n"
"")
        self.label_10.setObjectName("label_10")
        self.lne_yayin_evi = QtWidgets.QLineEdit(self.splitter_9)
        self.lne_yayin_evi.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lne_yayin_evi.setObjectName("lne_yayin_evi")
        self.verticalLayout_2.addWidget(self.splitter_9)
        self.splitter_10 = QtWidgets.QSplitter(self.layoutWidget4)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.label_11 = QtWidgets.QLabel(self.splitter_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);\n"
"")
        self.label_11.setObjectName("label_11")
        self.spb_kitap_sayfasi = QtWidgets.QSpinBox(self.splitter_10)
        self.spb_kitap_sayfasi.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.spb_kitap_sayfasi.setMaximum(999999)
        self.spb_kitap_sayfasi.setSingleStep(1)
        self.spb_kitap_sayfasi.setProperty("value", 150)
        self.spb_kitap_sayfasi.setObjectName("spb_kitap_sayfasi")
        self.verticalLayout_2.addWidget(self.splitter_10)
        self.splitter_19 = QtWidgets.QSplitter(self.tab_Kitap_ekle)
        self.splitter_19.setGeometry(QtCore.QRect(0, 390, 1139, 82))
        self.splitter_19.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_19.setObjectName("splitter_19")
        self.label_15 = QtWidgets.QLabel(self.splitter_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(221, 111, 0);\n"
"background-color: rgb(57, 57, 57);\n"
"")
        self.label_15.setObjectName("label_15")
        self.lne_raf = QtWidgets.QLineEdit(self.splitter_19)
        self.lne_raf.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lne_raf.setObjectName("lne_raf")
        self.pbt_kitaplara_git = QtWidgets.QPushButton(self.tab_Kitap_ekle)
        self.pbt_kitaplara_git.setGeometry(QtCore.QRect(1180, 20, 501, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbt_kitaplara_git.setFont(font)
        self.pbt_kitaplara_git.setStyleSheet("\n"
"background-color: rgb(255, 170, 0);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/next-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbt_kitaplara_git.setIcon(icon9)
        self.pbt_kitaplara_git.setIconSize(QtCore.QSize(24, 24))
        self.pbt_kitaplara_git.setObjectName("pbt_kitaplara_git")
        self.pbt_kaydet = QtWidgets.QPushButton(self.tab_Kitap_ekle)
        self.pbt_kaydet.setGeometry(QtCore.QRect(190, 550, 251, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pbt_kaydet.setFont(font)
        self.pbt_kaydet.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 127);")
        self.pbt_kaydet.setIcon(icon5)
        self.pbt_kaydet.setIconSize(QtCore.QSize(35, 35))
        self.pbt_kaydet.setObjectName("pbt_kaydet")
        self.tabWidget.addTab(self.tab_Kitap_ekle, icon8, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.splitter_17 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_17.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setObjectName("splitter_17")
        self.splitter_18 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_18.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.splitter_18.setOrientation(QtCore.Qt.Vertical)
        self.splitter_18.setObjectName("splitter_18")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2861, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.cmb_teslim.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KÜTÜPHANE"))
        self.pbt_giris.setText(_translate("MainWindow", "Giriş"))
        self.label.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.label_2.setText(_translate("MainWindow", "Parola "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_home), _translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "Kitap Listesi"))
        self.tablw_Kitap_listesi.setSortingEnabled(False)
        self.pbt_kitap_ara.setText(_translate("MainWindow", "Kitap Ara"))
        self.label_4.setText(_translate("MainWindow", "KİTAP"))
        self.label_5.setText(_translate("MainWindow", "YAZAR"))
        self.pbt_listele.setText(_translate("MainWindow", "Listele"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Kitaplar), _translate("MainWindow", "Kitaplar"))
        self.label_6.setText(_translate("MainWindow", "adı:"))
        self.lne_soyad.setText(_translate("MainWindow", "Soyadı:"))
        self.lne_sinif.setText(_translate("MainWindow", "Sınıf"))
        self.lne_gsm_no.setText(_translate("MainWindow", "GSM NO:"))
        self.label_18.setText(_translate("MainWindow", "Son Teslim Tarihi"))
        self.tablw_Kitap_listesi_2.setSortingEnabled(False)
        self.pbt_kul_kaydet.setText(_translate("MainWindow", "KAYDET"))
        self.label_14.setText(_translate("MainWindow", "Kitap Seç"))
        self.tablw_kullanicilar.setSortingEnabled(False)
        self.label_7.setText(_translate("MainWindow", "Kitap Adı:"))
        self.label_13.setText(_translate("MainWindow", "Yazar"))
        self.cmb_teslim.setItemText(0, _translate("MainWindow", "Teslim Edildi"))
        self.cmb_teslim.setItemText(1, _translate("MainWindow", "Teslim Edilmedi"))
        self.pbt_guncele.setText(_translate("MainWindow", "Gücele"))
        self.pbt_ara.setText(_translate("MainWindow", "ARA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kullanici_ekle), _translate("MainWindow", "Kullanıncılar -  Ekle"))
        self.label_8.setText(_translate("MainWindow", "Kitap Adı:"))
        self.label_9.setText(_translate("MainWindow", "Yazarı:"))
        self.label_10.setText(_translate("MainWindow", "Yayın Evi"))
        self.label_11.setText(_translate("MainWindow", "Sayfa Sayısı"))
        self.label_15.setText(_translate("MainWindow", "RAF "))
        self.pbt_kitaplara_git.setText(_translate("MainWindow", "KİTAPLAR MENÜSÜNE GİT"))
        self.pbt_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Kitap_ekle), _translate("MainWindow", "Kitap Ekle"))

import icosn_action_rc
